spring:
  profiles:
    active: dev


logging:
  level:
    duegin.ginDriver: debug


mybatis-flex:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: duegin.ginDriver.domain.po
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

