spring:
  profiles:
    active: dev
    include: log4j2
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
#  mvc:
#    format:
#      date-time: yyyy-MM-dd HH:mm:ss
#      date: yyyy-MM-dd
#      time: HH:mm:ss


logging:
  level:
    duegin.ginDriver: debug
#  config: classpath:log4j2/log4j2-dev.xml


mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ginDriver..domain.po
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
