spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB


logging:
  level:
    duegin.ginDriver: debug


mybatis-flex:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ginDriver.domain.po
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
